SYSTEMS = {
    'atari7800': {'name': 'Atari 7800',
                  'supported_exts': ['a78', 'bin']},
    'fds': {'name': 'Famicom Disk System'},
    'gamegear': {'name': 'Sega Game Gear',
                 'display_name': 'Game Gear',
                 'supported_exts': []},
    'gb': {'name': 'Nintendo Game Boy',
           'display_name': 'Game Boy'},
    'gba': {'name': 'Nintendo Game Boy Advance',
            'display_name': 'Game Boy Advance'},
    'gbc': {'name': 'Nintendo Game Boy Color',
            'display_name': 'Game Boy Color'},
    'gc': {'name': 'Nintendo GameCube',
           'display_name': 'GameCube',
           'supported_exts': ['iso']},
    'mastersystem': {'name': 'Sega Master System ',
                     'supported_exts': ['sms']},
    'megadrive': {'name': 'Sega Mega Drive',
                  'display_name': 'Sega Genesis/Mega Drive',
                  'aliases': ['Sega Genesis'],
                  'supported_exts': ['smd', 'bin', 'gen', 'md', 'sg', 'zip']},
    'n64': {'name': 'Nintendo 64',
            'supported_exts': ['z64', 'n64', 'v64']},
    'nes': {'name': 'Nintendo Entertainment System (NES)',
            'display_name': 'NES',
            'supported_exts': ['zip', 'nes', 'smc', 'sfc',
                               'fig', 'swc', 'mgd']},
    'pcengine': {'name': 'TurboGrafx 16',
                 'supported_exts': ['pce']},
    'ps2': {'name': 'Sony Playstation 2',
            'display_name': 'PS2',
            'supported_exts': ['iso', 'img', 'bin', 'mdf', 'z', 'z2',
                               'bz2', 'dump', 'cso', 'ima', 'gz']},
    'psp': {'name': 'Sony Playstation Portable',
            'display_name': 'PSP',
            'supported_exts': ['cso', 'iso', 'pbp']},
    'psx': {'name': 'Sony Playstation',
            'display_name': 'Playstation',
            'supported_exts': ['cue', 'cbn', 'img', 'iso', 'm3u',
                               'mdf', 'pbp', 'toc', 'z', 'znx']},
    'snes': {'name': 'Super Nintendo (SNES)',
             'display_name': 'Super Nintendo',
             'supported_exts': ['zip', 'smc', 'sfc', 'fig', 'swc']}
}
